[2024-10-16T17:46:17.194+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-10-16T17:46:17.268+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.STRK scheduled__2024-10-02T09:00:00+00:00 [queued]>
[2024-10-16T17:46:17.303+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.STRK scheduled__2024-10-02T09:00:00+00:00 [queued]>
[2024-10-16T17:46:17.306+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 6
[2024-10-16T17:46:17.362+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): STRK> on 2024-10-02 09:00:00+00:00
[2024-10-16T17:46:17.382+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2024-10-16T17:46:17.392+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'STRK', 'scheduled__2024-10-02T09:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpntdultbm']
[2024-10-16T17:46:17.399+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask STRK
[2024-10-16T17:46:17.462+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-16T17:46:27.575+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 136 for task STRK ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 77)
[2024-10-16T17:46:29.186+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-16T17:46:29.458+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
