[2024-10-16T17:40:24.137+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-10-16T17:40:24.283+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.SOL scheduled__2024-10-01T09:00:00+00:00 [queued]>
[2024-10-16T17:40:24.463+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.SOL scheduled__2024-10-01T09:00:00+00:00 [queued]>
[2024-10-16T17:40:24.465+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2024-10-16T17:40:25.280+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): SOL> on 2024-10-01 09:00:00+00:00
[2024-10-16T17:40:25.301+0000] {standard_task_runner.py:57} INFO - Started process 173 to run task
[2024-10-16T17:40:25.335+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'SOL', 'scheduled__2024-10-01T09:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmp293xv6vc']
[2024-10-16T17:40:25.357+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask SOL
[2024-10-16T17:40:25.472+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-10-16T17:40:36.579+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 65 for task SOL ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 173)
[2024-10-16T17:40:38.532+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-10-16T17:40:48.242+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
