[2024-09-30T14:20:46.578+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:20:46.580+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:20:46.582+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:20:46.582+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:20:49.006+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:20:48.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:20:49.010+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:20:49.109+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 2.545 seconds
[2024-09-30T14:21:19.852+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:21:19.855+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:21:19.860+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:21:19.859+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:22:46.733+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:22:46.735+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:22:46.737+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:22:46.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:22:48.384+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:22:48.372+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:22:48.388+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:22:48.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 2.008 seconds
[2024-09-30T14:23:19.028+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:19.029+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:23:19.099+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:19.098+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:21.765+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:21.508+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:23:21.768+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:21.817+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 2.796 seconds
[2024-09-30T14:23:52.042+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:52.043+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:23:52.044+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:52.044+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:52.939+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:52.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:23:52.941+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:23:53.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 1.329 seconds
[2024-09-30T14:24:24.025+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:24.028+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:24:24.031+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:24.030+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:25.677+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:25.641+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:24:25.680+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:25.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 1.837 seconds
[2024-09-30T14:24:55.980+0000] {processor.py:157} INFO - Started process (PID=147) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:55.982+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:24:55.984+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:55.984+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:57.377+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:57.371+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:24:57.379+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:24:57.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 1.689 seconds
[2024-09-30T14:25:28.302+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:25:28.305+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:25:28.307+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:28.307+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:25:29.225+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:29.217+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:25:29.227+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:25:29.260+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.965 seconds
[2024-09-30T14:25:59.570+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:25:59.574+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:25:59.576+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:59.575+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:26:00.284+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:00.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:26:00.287+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:26:00.327+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.765 seconds
[2024-09-30T14:26:31.064+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:26:31.271+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:26:31.274+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:31.273+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:26:32.292+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:32.082+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:26:32.294+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:26:33.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 2.482 seconds
[2024-09-30T14:27:04.438+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:04.440+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:27:04.442+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:04.442+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:05.050+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:05.041+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:27:05.053+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:05.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.659 seconds
[2024-09-30T14:27:35.530+0000] {processor.py:157} INFO - Started process (PID=282) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:35.532+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:27:35.535+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:35.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:36.190+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:36.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:27:36.193+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:27:36.227+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.703 seconds
[2024-09-30T14:28:06.952+0000] {processor.py:157} INFO - Started process (PID=322) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:06.955+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:28:06.958+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:06.957+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:07.602+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:07.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:28:07.604+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:07.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.684 seconds
[2024-09-30T14:28:37.949+0000] {processor.py:157} INFO - Started process (PID=350) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:37.951+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:28:37.952+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:37.952+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:38.578+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:38.567+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:28:38.582+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:28:38.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.689 seconds
[2024-09-30T14:29:09.030+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:09.042+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:29:09.044+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:09.043+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:09.607+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:09.600+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:29:09.610+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:09.646+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.620 seconds
[2024-09-30T14:29:39.876+0000] {processor.py:157} INFO - Started process (PID=404) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:39.878+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:29:39.880+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:39.879+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:40.347+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:40.336+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:29:40.349+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:29:40.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.515 seconds
[2024-09-30T14:30:10.799+0000] {processor.py:157} INFO - Started process (PID=418) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:10.801+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:30:10.805+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:10.804+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:11.689+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:11.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:30:11.691+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:11.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.938 seconds
[2024-09-30T14:30:42.186+0000] {processor.py:157} INFO - Started process (PID=445) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:42.188+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:30:42.189+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:42.189+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:42.908+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:42.900+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:30:42.910+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:30:42.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.765 seconds
[2024-09-30T14:31:13.726+0000] {processor.py:157} INFO - Started process (PID=472) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:13.729+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:31:13.731+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:13.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:14.401+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:14.386+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:31:14.403+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:14.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.728 seconds
[2024-09-30T14:31:44.566+0000] {processor.py:157} INFO - Started process (PID=499) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:44.568+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:31:44.570+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:44.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:45.205+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:45.194+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:31:45.209+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:31:45.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.687 seconds
[2024-09-30T14:32:15.701+0000] {processor.py:157} INFO - Started process (PID=526) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:15.703+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:32:15.705+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:15.705+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:16.305+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:16.297+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:32:16.307+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:16.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.650 seconds
[2024-09-30T14:32:46.796+0000] {processor.py:157} INFO - Started process (PID=553) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:46.798+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:32:46.800+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:46.800+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:47.482+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:47.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:32:47.486+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:32:47.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.788 seconds
[2024-09-30T14:33:17.805+0000] {processor.py:157} INFO - Started process (PID=580) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:17.807+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:33:17.810+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:17.809+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:18.433+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:18.425+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:33:18.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:18.478+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.677 seconds
[2024-09-30T14:33:48.917+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:48.919+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:33:48.921+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:48.920+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:49.553+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:49.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:33:49.555+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:33:49.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.789 seconds
[2024-09-30T14:34:20.492+0000] {processor.py:157} INFO - Started process (PID=634) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:20.495+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:34:20.498+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:20.497+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:21.094+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:21.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:34:21.096+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:21.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.641 seconds
[2024-09-30T14:34:51.574+0000] {processor.py:157} INFO - Started process (PID=661) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:51.575+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:34:51.577+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:51.576+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:52.218+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:52.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:34:52.220+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:34:52.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.678 seconds
[2024-09-30T14:35:22.685+0000] {processor.py:157} INFO - Started process (PID=688) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:22.687+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:35:22.689+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:22.689+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:23.384+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:23.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:35:23.386+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:23.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.732 seconds
[2024-09-30T14:35:54.292+0000] {processor.py:157} INFO - Started process (PID=728) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:54.294+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:35:54.297+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:54.296+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:55.336+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:55.326+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:35:55.339+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:35:55.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 1.090 seconds
[2024-09-30T14:36:25.721+0000] {processor.py:157} INFO - Started process (PID=755) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:25.723+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:36:25.725+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:25.724+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:26.211+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:26.203+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:36:26.213+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:26.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.656 seconds
[2024-09-30T14:36:56.628+0000] {processor.py:157} INFO - Started process (PID=781) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:56.630+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:36:56.631+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:56.631+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:57.340+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:57.331+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:36:57.342+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:36:59.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 2.608 seconds
[2024-09-30T14:37:29.293+0000] {processor.py:157} INFO - Started process (PID=796) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:37:29.295+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:37:29.296+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:37:29.296+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:37:29.912+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:37:29.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:37:29.915+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:37:29.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.674 seconds
[2024-09-30T14:38:00.516+0000] {processor.py:157} INFO - Started process (PID=823) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:00.522+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:38:00.525+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:00.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:01.160+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:01.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:38:01.161+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:01.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.689 seconds
[2024-09-30T14:38:31.619+0000] {processor.py:157} INFO - Started process (PID=850) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:31.621+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:38:31.623+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:31.623+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:32.261+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:32.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:38:32.264+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:38:32.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.682 seconds
[2024-09-30T14:39:02.396+0000] {processor.py:157} INFO - Started process (PID=877) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:02.398+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:39:02.400+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:02.399+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:03.012+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:03.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:39:03.015+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:03.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.661 seconds
[2024-09-30T14:39:33.480+0000] {processor.py:157} INFO - Started process (PID=904) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:33.481+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:39:33.483+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:33.482+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:34.030+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:34.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:39:34.032+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:39:34.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.586 seconds
[2024-09-30T14:40:04.263+0000] {processor.py:157} INFO - Started process (PID=931) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:04.265+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:40:04.266+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:04.266+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:04.900+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:04.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:40:04.903+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:04.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.678 seconds
[2024-09-30T14:40:35.377+0000] {processor.py:157} INFO - Started process (PID=958) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:35.379+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:40:35.380+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:35.380+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:36.002+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:35.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:40:36.005+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:40:36.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.664 seconds
[2024-09-30T14:41:06.459+0000] {processor.py:157} INFO - Started process (PID=985) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:06.460+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:41:06.462+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:06.462+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:07.061+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:07.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:41:07.064+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:07.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.650 seconds
[2024-09-30T14:41:37.543+0000] {processor.py:157} INFO - Started process (PID=1012) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:37.545+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:41:37.547+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:37.547+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:38.135+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:38.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:41:38.139+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:41:38.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.633 seconds
[2024-09-30T14:42:08.609+0000] {processor.py:157} INFO - Started process (PID=1039) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:08.611+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:42:08.614+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:08.614+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:09.334+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:09.326+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:42:09.337+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:09.369+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.767 seconds
[2024-09-30T14:42:39.787+0000] {processor.py:157} INFO - Started process (PID=1066) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:39.789+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:42:39.790+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:39.790+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:40.424+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:40.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:42:40.426+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:42:40.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.669 seconds
[2024-09-30T14:43:10.564+0000] {processor.py:157} INFO - Started process (PID=1093) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:10.566+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:43:10.568+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:10.568+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:11.183+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:11.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:43:11.186+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:11.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.665 seconds
[2024-09-30T14:43:41.663+0000] {processor.py:157} INFO - Started process (PID=1120) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:41.665+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:43:41.668+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:41.667+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:42.300+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:42.292+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:43:42.303+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:43:42.335+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.678 seconds
[2024-09-30T14:44:12.458+0000] {processor.py:157} INFO - Started process (PID=1147) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:44:12.459+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T14:44:12.461+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:44:12.461+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:44:13.079+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:44:13.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:44:13.081+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T14:44:13.114+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.660 seconds
[2024-09-30T20:06:41.482+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:06:41.485+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:06:41.487+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:06:41.486+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:06:42.277+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:06:42.273+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:06:42.279+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:06:42.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.824 seconds
[2024-09-30T20:07:12.605+0000] {processor.py:157} INFO - Started process (PID=65) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:12.606+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:07:12.608+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:12.607+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:13.242+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:13.236+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:07:13.244+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:13.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.666 seconds
[2024-09-30T20:07:43.594+0000] {processor.py:157} INFO - Started process (PID=92) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:43.595+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:07:43.596+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:43.596+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:44.200+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:44.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:07:44.202+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:07:44.226+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.636 seconds
[2024-09-30T20:08:14.570+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:14.571+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:08:14.573+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:14.573+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:15.198+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:15.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:08:15.200+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:15.221+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.654 seconds
[2024-09-30T20:08:45.539+0000] {processor.py:157} INFO - Started process (PID=146) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:45.540+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:08:45.542+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:45.541+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:46.149+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:46.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:08:46.151+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:08:46.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.638 seconds
[2024-09-30T20:09:16.480+0000] {processor.py:157} INFO - Started process (PID=173) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:16.481+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:09:16.482+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:16.482+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:17.071+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:17.065+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:09:17.073+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:17.093+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.617 seconds
[2024-09-30T20:09:47.412+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:47.413+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:09:47.415+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:47.414+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:48.055+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:48.050+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:09:48.057+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:09:48.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.668 seconds
[2024-09-30T20:10:18.489+0000] {processor.py:157} INFO - Started process (PID=227) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:18.491+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:10:18.492+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:18.492+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:18.929+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:18.922+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:10:18.930+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:18.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.468 seconds
[2024-09-30T20:10:49.295+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:49.297+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:10:49.298+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:49.298+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:49.779+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:49.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:10:49.781+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:10:49.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.515 seconds
[2024-09-30T20:11:20.132+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:20.133+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:11:20.135+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:20.135+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:20.596+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:20.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:11:20.597+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:20.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.497 seconds
[2024-09-30T20:11:51.012+0000] {processor.py:157} INFO - Started process (PID=308) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:51.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:11:51.015+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:51.015+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:51.559+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:51.552+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:11:51.561+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:11:51.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.581 seconds
[2024-09-30T20:12:21.939+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:21.940+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:12:21.942+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:21.941+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:22.373+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:22.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:12:22.375+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:22.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.462 seconds
[2024-09-30T20:12:52.717+0000] {processor.py:157} INFO - Started process (PID=362) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:52.718+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:12:52.719+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:52.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:53.185+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:53.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:12:53.186+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:12:53.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.494 seconds
[2024-09-30T20:13:23.519+0000] {processor.py:157} INFO - Started process (PID=389) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:23.520+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:13:23.522+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:23.521+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:23.949+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:23.942+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:13:23.951+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:23.973+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.457 seconds
[2024-09-30T20:13:54.308+0000] {processor.py:157} INFO - Started process (PID=416) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:54.310+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:13:54.311+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:54.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:54.748+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:54.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:13:54.750+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:13:54.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.472 seconds
[2024-09-30T20:14:25.098+0000] {processor.py:157} INFO - Started process (PID=443) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:25.099+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:14:25.101+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:25.100+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:25.557+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:25.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:14:25.560+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:25.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.497 seconds
[2024-09-30T20:14:55.930+0000] {processor.py:157} INFO - Started process (PID=470) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:55.932+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:14:55.933+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:55.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:56.371+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:56.364+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:14:56.373+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:14:56.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.469 seconds
[2024-09-30T20:15:26.702+0000] {processor.py:157} INFO - Started process (PID=497) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:26.703+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:15:26.705+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:26.704+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:27.286+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:27.278+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:15:27.289+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:27.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.616 seconds
[2024-09-30T20:15:57.649+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:57.650+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:15:57.652+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:57.651+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:58.112+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:58.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:15:58.114+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:15:58.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.492 seconds
[2024-09-30T20:16:28.474+0000] {processor.py:157} INFO - Started process (PID=551) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:28.475+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:16:28.477+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:28.477+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:28.909+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:28.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:16:28.911+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:28.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.464 seconds
[2024-09-30T20:16:59.309+0000] {processor.py:157} INFO - Started process (PID=578) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:59.310+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:16:59.311+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:59.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:59.744+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:59.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:16:59.746+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:16:59.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.468 seconds
[2024-09-30T20:17:30.100+0000] {processor.py:157} INFO - Started process (PID=605) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:17:30.101+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:17:30.103+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:17:30.102+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:17:30.615+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:17:30.608+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:17:30.617+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:17:30.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.551 seconds
[2024-09-30T20:18:01.048+0000] {processor.py:157} INFO - Started process (PID=632) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:01.049+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:18:01.050+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:01.050+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:01.481+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:01.474+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:18:01.483+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:01.506+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.462 seconds
[2024-09-30T20:18:31.841+0000] {processor.py:157} INFO - Started process (PID=659) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:31.842+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:18:31.843+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:31.843+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:32.266+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:32.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:18:32.267+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:18:32.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.458 seconds
[2024-09-30T20:19:02.620+0000] {processor.py:157} INFO - Started process (PID=686) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:02.621+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:19:02.622+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:02.622+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:03.096+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:03.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:19:03.097+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:03.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.510 seconds
[2024-09-30T20:19:33.458+0000] {processor.py:157} INFO - Started process (PID=713) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:33.459+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:19:33.460+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:33.460+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:33.900+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:33.894+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:19:33.902+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:19:33.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.468 seconds
[2024-09-30T20:20:04.246+0000] {processor.py:157} INFO - Started process (PID=740) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:04.247+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:20:04.248+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:04.248+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:04.698+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:04.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:20:04.700+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:04.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.485 seconds
[2024-09-30T20:20:35.044+0000] {processor.py:157} INFO - Started process (PID=767) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:35.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:20:35.046+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:35.046+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:35.516+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:35.510+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:20:35.518+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:20:35.543+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.503 seconds
[2024-09-30T20:21:05.862+0000] {processor.py:157} INFO - Started process (PID=794) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:05.863+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:21:05.865+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:05.864+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:06.371+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:06.364+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:21:06.373+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:06.398+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.542 seconds
[2024-09-30T20:21:36.707+0000] {processor.py:157} INFO - Started process (PID=821) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:36.709+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:21:36.710+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:36.710+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:37.186+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:37.180+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:21:37.188+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:21:37.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.508 seconds
[2024-09-30T20:22:07.577+0000] {processor.py:157} INFO - Started process (PID=848) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:07.578+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:22:07.579+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:07.579+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:08.052+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:08.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:22:08.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:08.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.509 seconds
[2024-09-30T20:22:38.409+0000] {processor.py:157} INFO - Started process (PID=875) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:38.411+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:22:38.412+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:38.411+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:38.899+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:38.893+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:22:38.901+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:22:38.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.516 seconds
[2024-09-30T20:23:09.224+0000] {processor.py:157} INFO - Started process (PID=902) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:09.225+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:23:09.226+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:09.226+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:09.780+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:09.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:23:09.782+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:09.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.587 seconds
[2024-09-30T20:23:40.102+0000] {processor.py:157} INFO - Started process (PID=929) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:40.103+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:23:40.104+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:40.104+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:40.553+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:40.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:23:40.555+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:23:40.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.480 seconds
[2024-09-30T20:24:10.907+0000] {processor.py:157} INFO - Started process (PID=956) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:10.908+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:24:10.909+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:10.909+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:11.443+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:11.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:24:11.445+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:11.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.572 seconds
[2024-09-30T20:24:41.800+0000] {processor.py:157} INFO - Started process (PID=983) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:41.801+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:24:41.802+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:41.802+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:42.289+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:42.282+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:24:42.293+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:24:42.320+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.524 seconds
[2024-09-30T20:25:12.658+0000] {processor.py:157} INFO - Started process (PID=1010) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:12.660+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:25:12.661+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:12.661+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:13.205+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:13.199+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:25:13.206+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:13.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.575 seconds
[2024-09-30T20:25:43.527+0000] {processor.py:157} INFO - Started process (PID=1037) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:43.528+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:25:43.530+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:43.529+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:44.030+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:44.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:25:44.032+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:25:44.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.541 seconds
[2024-09-30T20:26:14.373+0000] {processor.py:157} INFO - Started process (PID=1064) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:14.374+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:26:14.375+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:14.375+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:14.835+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:14.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:26:14.836+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:14.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.491 seconds
[2024-09-30T20:26:45.208+0000] {processor.py:157} INFO - Started process (PID=1091) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:45.209+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:26:45.210+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:45.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:45.667+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:45.661+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:26:45.669+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:26:45.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.493 seconds
[2024-09-30T20:27:16.004+0000] {processor.py:157} INFO - Started process (PID=1118) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:16.006+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:27:16.007+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:16.007+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:16.478+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:16.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:27:16.479+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:16.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.501 seconds
[2024-09-30T20:27:46.827+0000] {processor.py:157} INFO - Started process (PID=1145) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:46.828+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:27:46.830+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:46.829+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:47.379+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:47.372+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:27:47.381+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:27:47.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.585 seconds
[2024-09-30T20:28:17.716+0000] {processor.py:157} INFO - Started process (PID=1172) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:17.718+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:28:17.719+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:17.718+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:18.161+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:18.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:28:18.163+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:18.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.478 seconds
[2024-09-30T20:28:48.497+0000] {processor.py:157} INFO - Started process (PID=1199) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:48.498+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:28:48.500+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:48.500+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:49.012+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:49.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:28:49.014+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:28:49.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.542 seconds
[2024-09-30T20:29:19.327+0000] {processor.py:157} INFO - Started process (PID=1226) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:19.329+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:29:19.331+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:19.330+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:19.867+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:19.860+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:29:19.869+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:19.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.577 seconds
[2024-09-30T20:29:50.201+0000] {processor.py:157} INFO - Started process (PID=1253) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:50.202+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:29:50.203+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:50.203+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:50.691+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:50.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:29:50.693+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:29:50.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.524 seconds
[2024-09-30T20:30:21.034+0000] {processor.py:157} INFO - Started process (PID=1280) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:21.036+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:30:21.037+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:21.037+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:21.541+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:21.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:30:21.543+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:21.572+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.542 seconds
[2024-09-30T20:30:51.914+0000] {processor.py:157} INFO - Started process (PID=1307) to work on /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:51.916+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag1.py for tasks to queue
[2024-09-30T20:30:51.917+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:51.917+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:52.531+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:52.523+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag1.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:30:52.533+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag1.py
[2024-09-30T20:30:52.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag1.py took 0.669 seconds
