[2024-09-30T14:20:46.587+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:20:46.588+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:20:46.590+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:20:46.590+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:20:49.006+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:20:48.993+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:20:49.010+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:20:49.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 2.507 seconds
[2024-09-30T14:21:19.866+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:21:19.868+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:21:19.870+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:21:19.870+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:21:23.665+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:21:23.664+0000] {process_utils.py:258} INFO - Waiting up to 5 seconds for processes to exit...
[2024-09-30T14:21:24.125+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:21:24.125+0000] {process_utils.py:258} INFO - Waiting up to 5 seconds for processes to exit...
[2024-09-30T14:22:46.756+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:22:46.759+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:22:46.761+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:22:46.761+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:22:48.482+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:22:48.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:22:48.485+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:22:48.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 1.987 seconds
[2024-09-30T14:23:19.038+0000] {processor.py:157} INFO - Started process (PID=67) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:19.157+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:23:19.159+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:19.158+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:21.764+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:21.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:23:21.767+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:21.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 2.788 seconds
[2024-09-30T14:23:52.051+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:52.052+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:23:52.053+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:52.053+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:52.912+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:23:52.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:23:52.915+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:23:53.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 1.319 seconds
[2024-09-30T14:24:24.062+0000] {processor.py:157} INFO - Started process (PID=121) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:24.066+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:24:24.069+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:24.068+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:25.731+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:25.723+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:24:25.733+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:25.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 1.926 seconds
[2024-09-30T14:24:56.566+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:56.569+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:24:56.572+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:56.571+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:57.480+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:24:57.472+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:24:57.538+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:24:57.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 1.265 seconds
[2024-09-30T14:25:28.321+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:25:28.323+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:25:28.325+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:28.324+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:25:29.240+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:29.233+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:25:29.242+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:25:29.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.966 seconds
[2024-09-30T14:25:59.591+0000] {processor.py:157} INFO - Started process (PID=202) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:25:59.594+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:25:59.596+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:25:59.596+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:26:00.291+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:00.282+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:26:00.293+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:26:00.329+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.747 seconds
[2024-09-30T14:26:31.073+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:26:31.272+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:26:31.274+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:31.273+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:26:32.083+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:26:32.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:26:32.289+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:26:33.542+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 2.473 seconds
[2024-09-30T14:27:04.451+0000] {processor.py:157} INFO - Started process (PID=256) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:04.452+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:27:04.454+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:04.454+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:05.083+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:05.074+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:27:05.085+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:05.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.670 seconds
[2024-09-30T14:27:35.545+0000] {processor.py:157} INFO - Started process (PID=283) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:35.546+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:27:35.548+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:35.548+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:36.181+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:27:36.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:27:36.184+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:27:36.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.686 seconds
[2024-09-30T14:28:06.299+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:06.301+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:28:06.302+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:06.302+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:06.847+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:06.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:28:06.850+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:06.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.588 seconds
[2024-09-30T14:28:36.980+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:36.982+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:28:36.984+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:36.983+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:37.521+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:28:37.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:28:37.523+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:28:37.562+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.586 seconds
[2024-09-30T14:29:08.036+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:08.038+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:29:08.040+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:08.040+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:08.938+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:08.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:29:08.940+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:08.974+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.948 seconds
[2024-09-30T14:29:39.139+0000] {processor.py:157} INFO - Started process (PID=391) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:39.140+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:29:39.142+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:39.142+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:39.787+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:29:39.777+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:29:39.789+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:29:39.822+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.687 seconds
[2024-09-30T14:30:10.817+0000] {processor.py:157} INFO - Started process (PID=419) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:10.820+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:30:10.822+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:10.822+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:11.688+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:11.680+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:30:11.691+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:11.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.924 seconds
[2024-09-30T14:30:42.199+0000] {processor.py:157} INFO - Started process (PID=446) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:42.201+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:30:42.202+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:42.202+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:42.904+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:30:42.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:30:42.906+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:30:42.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.751 seconds
[2024-09-30T14:31:13.741+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:13.743+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:31:13.744+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:13.744+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:14.416+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:14.408+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:31:14.418+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:14.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.725 seconds
[2024-09-30T14:31:44.582+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:44.584+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:31:44.587+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:44.586+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:45.255+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:31:45.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:31:45.259+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:31:45.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.723 seconds
[2024-09-30T14:32:15.717+0000] {processor.py:157} INFO - Started process (PID=527) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:15.719+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:32:15.720+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:15.720+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:16.319+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:16.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:32:16.322+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:16.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.703 seconds
[2024-09-30T14:32:46.808+0000] {processor.py:157} INFO - Started process (PID=554) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:46.810+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:32:46.811+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:46.811+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:47.502+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:32:47.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:32:47.505+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:32:47.581+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.778 seconds
[2024-09-30T14:33:17.820+0000] {processor.py:157} INFO - Started process (PID=581) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:17.822+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:33:17.824+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:17.823+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:18.451+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:18.441+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:33:18.454+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:18.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.672 seconds
[2024-09-30T14:33:48.929+0000] {processor.py:157} INFO - Started process (PID=608) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:48.931+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:33:48.933+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:48.933+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:49.561+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:33:49.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:33:49.563+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:33:49.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.777 seconds
[2024-09-30T14:34:20.509+0000] {processor.py:157} INFO - Started process (PID=635) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:20.511+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:34:20.512+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:20.512+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:21.115+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:21.106+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:34:21.117+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:21.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.639 seconds
[2024-09-30T14:34:51.588+0000] {processor.py:157} INFO - Started process (PID=662) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:51.590+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:34:51.592+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:51.592+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:52.231+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:34:52.224+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:34:52.233+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:34:52.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.675 seconds
[2024-09-30T14:35:22.698+0000] {processor.py:157} INFO - Started process (PID=689) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:22.700+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:35:22.702+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:22.702+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:23.379+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:23.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:35:23.381+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:23.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.718 seconds
[2024-09-30T14:35:53.527+0000] {processor.py:157} INFO - Started process (PID=715) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:53.530+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:35:53.532+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:53.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:54.563+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:35:54.555+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:35:54.566+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:35:54.608+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 1.097 seconds
[2024-09-30T14:36:25.010+0000] {processor.py:157} INFO - Started process (PID=742) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:25.011+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:36:25.014+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:25.013+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:25.546+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:25.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:36:25.550+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:25.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.649 seconds
[2024-09-30T14:36:56.373+0000] {processor.py:157} INFO - Started process (PID=769) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:56.375+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:36:56.376+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:56.376+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:57.310+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:36:57.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:36:57.313+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:36:59.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 2.859 seconds
[2024-09-30T14:37:29.303+0000] {processor.py:157} INFO - Started process (PID=797) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:37:29.304+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:37:29.306+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:37:29.306+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:37:29.894+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:37:29.886+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:37:29.897+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:37:29.945+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.646 seconds
[2024-09-30T14:38:00.533+0000] {processor.py:157} INFO - Started process (PID=824) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:00.535+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:38:00.538+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:00.537+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:01.179+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:01.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:38:01.182+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:01.210+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.684 seconds
[2024-09-30T14:38:31.633+0000] {processor.py:157} INFO - Started process (PID=851) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:31.635+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:38:31.636+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:31.636+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:32.248+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:38:32.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:38:32.250+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:38:32.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.658 seconds
[2024-09-30T14:39:02.409+0000] {processor.py:157} INFO - Started process (PID=878) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:02.410+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:39:02.412+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:02.412+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:03.026+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:03.017+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:39:03.030+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:03.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.660 seconds
[2024-09-30T14:39:33.491+0000] {processor.py:157} INFO - Started process (PID=905) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:33.492+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:39:33.494+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:33.493+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:34.030+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:39:34.023+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:39:34.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:39:34.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.576 seconds
[2024-09-30T14:40:04.275+0000] {processor.py:157} INFO - Started process (PID=932) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:04.278+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:40:04.279+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:04.279+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:04.917+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:04.909+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:40:04.919+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:04.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.681 seconds
[2024-09-30T14:40:35.390+0000] {processor.py:157} INFO - Started process (PID=959) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:35.392+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:40:35.394+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:35.393+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:35.981+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:40:35.973+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:40:35.983+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:40:36.022+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.637 seconds
[2024-09-30T14:41:06.471+0000] {processor.py:157} INFO - Started process (PID=986) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:06.472+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:41:06.473+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:06.473+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:07.094+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:07.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:41:07.096+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:07.134+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.668 seconds
[2024-09-30T14:41:37.554+0000] {processor.py:157} INFO - Started process (PID=1013) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:37.555+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:41:37.557+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:37.556+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:38.174+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:41:38.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:41:38.177+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:41:38.209+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.660 seconds
[2024-09-30T14:42:08.622+0000] {processor.py:157} INFO - Started process (PID=1040) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:08.624+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:42:08.626+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:08.626+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:09.360+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:09.351+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:42:09.362+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:09.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.780 seconds
[2024-09-30T14:42:39.804+0000] {processor.py:157} INFO - Started process (PID=1067) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:39.805+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:42:39.806+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:39.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:40.424+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:42:40.417+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:42:40.426+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:42:40.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.654 seconds
[2024-09-30T14:43:10.578+0000] {processor.py:157} INFO - Started process (PID=1094) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:10.580+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:43:10.582+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:10.582+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:11.204+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:11.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:43:11.207+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:11.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.665 seconds
[2024-09-30T14:43:41.679+0000] {processor.py:157} INFO - Started process (PID=1121) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:41.681+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:43:41.683+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:41.683+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:42.305+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:43:42.296+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:43:42.308+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:43:42.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.669 seconds
[2024-09-30T14:44:12.470+0000] {processor.py:157} INFO - Started process (PID=1148) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:44:12.471+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T14:44:12.472+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:44:12.472+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:44:13.102+0000] {logging_mixin.py:149} INFO - [2024-09-30T14:44:13.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T14:44:13.104+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T14:44:13.137+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.673 seconds
[2024-09-30T20:06:41.496+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:06:41.498+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:06:41.500+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:06:41.499+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:06:42.260+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:06:42.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:06:42.262+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:06:42.284+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.793 seconds
[2024-09-30T20:07:12.614+0000] {processor.py:157} INFO - Started process (PID=66) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:12.616+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:07:12.617+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:12.617+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:13.270+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:13.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:07:13.272+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:13.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.684 seconds
[2024-09-30T20:07:43.602+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:43.603+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:07:43.604+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:43.604+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:44.238+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:07:44.233+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:07:44.240+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:07:44.265+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.666 seconds
[2024-09-30T20:08:14.579+0000] {processor.py:157} INFO - Started process (PID=120) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:14.580+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:08:14.581+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:14.581+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:15.197+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:15.192+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:08:15.199+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:15.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.646 seconds
[2024-09-30T20:08:45.549+0000] {processor.py:157} INFO - Started process (PID=147) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:45.551+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:08:45.552+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:45.552+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:46.159+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:08:46.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:08:46.161+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:08:46.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.637 seconds
[2024-09-30T20:09:16.489+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:16.490+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:09:16.491+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:16.491+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:17.082+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:17.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:09:17.084+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:17.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.618 seconds
[2024-09-30T20:09:47.421+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:47.422+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:09:47.423+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:47.423+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:48.063+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:09:48.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:09:48.065+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:09:48.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.669 seconds
[2024-09-30T20:10:18.498+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:18.499+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:10:18.500+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:18.500+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:18.949+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:18.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:10:18.951+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:18.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.476 seconds
[2024-09-30T20:10:49.305+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:49.307+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:10:49.308+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:49.308+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:49.779+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:10:49.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:10:49.781+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:10:49.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.503 seconds
[2024-09-30T20:11:20.140+0000] {processor.py:157} INFO - Started process (PID=282) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:20.141+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:11:20.142+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:20.142+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:20.597+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:20.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:11:20.599+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:20.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.488 seconds
[2024-09-30T20:11:51.023+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:51.025+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:11:51.026+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:51.026+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:51.582+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:11:51.574+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:11:51.584+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:11:51.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.601 seconds
[2024-09-30T20:12:21.947+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:21.949+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:12:21.950+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:21.949+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:22.373+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:22.367+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:12:22.375+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:22.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.452 seconds
[2024-09-30T20:12:52.726+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:52.727+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:12:52.728+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:52.728+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:53.190+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:12:53.184+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:12:53.192+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:12:53.214+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.491 seconds
[2024-09-30T20:13:23.527+0000] {processor.py:157} INFO - Started process (PID=390) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:23.528+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:13:23.529+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:23.529+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:23.972+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:23.966+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:13:23.974+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:23.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.471 seconds
[2024-09-30T20:13:54.317+0000] {processor.py:157} INFO - Started process (PID=417) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:54.318+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:13:54.319+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:54.319+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:54.751+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:13:54.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:13:54.753+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:13:54.778+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.463 seconds
[2024-09-30T20:14:25.107+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:25.108+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:14:25.109+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:25.108+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:25.561+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:25.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:14:25.563+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:25.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.488 seconds
[2024-09-30T20:14:55.939+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:55.940+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:14:55.941+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:55.941+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:56.378+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:14:56.372+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:14:56.381+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:14:56.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.468 seconds
[2024-09-30T20:15:26.711+0000] {processor.py:157} INFO - Started process (PID=498) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:26.712+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:15:26.713+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:26.713+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:27.310+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:27.302+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:15:27.312+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:27.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.629 seconds
[2024-09-30T20:15:57.658+0000] {processor.py:157} INFO - Started process (PID=525) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:57.660+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:15:57.661+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:57.661+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:58.137+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:15:58.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:15:58.139+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:15:58.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.510 seconds
[2024-09-30T20:16:28.483+0000] {processor.py:157} INFO - Started process (PID=552) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:28.484+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:16:28.485+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:28.485+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:28.919+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:28.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:16:28.921+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:28.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.466 seconds
[2024-09-30T20:16:59.316+0000] {processor.py:157} INFO - Started process (PID=579) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:59.317+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:16:59.318+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:59.318+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:59.752+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:16:59.747+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:16:59.754+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:16:59.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.463 seconds
[2024-09-30T20:17:30.111+0000] {processor.py:157} INFO - Started process (PID=606) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:17:30.112+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:17:30.113+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:17:30.113+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:17:30.709+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:17:30.701+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:17:30.711+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:17:30.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.635 seconds
[2024-09-30T20:18:01.057+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:01.058+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:18:01.059+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:01.059+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:01.514+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:01.509+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:18:01.515+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:01.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.483 seconds
[2024-09-30T20:18:31.849+0000] {processor.py:157} INFO - Started process (PID=660) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:31.850+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:18:31.851+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:31.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:32.285+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:18:32.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:18:32.286+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:18:32.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.466 seconds
[2024-09-30T20:19:02.629+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:02.630+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:19:02.631+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:02.630+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:03.099+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:03.093+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:19:03.101+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:03.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.504 seconds
[2024-09-30T20:19:33.467+0000] {processor.py:157} INFO - Started process (PID=714) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:33.468+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:19:33.469+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:33.468+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:33.887+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:19:33.880+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:19:33.889+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:19:33.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.448 seconds
[2024-09-30T20:20:04.256+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:04.257+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:20:04.258+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:04.258+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:04.710+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:04.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:20:04.712+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:04.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.482 seconds
[2024-09-30T20:20:35.054+0000] {processor.py:157} INFO - Started process (PID=768) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:35.055+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:20:35.056+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:35.056+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:35.525+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:20:35.519+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:20:35.527+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:20:35.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.500 seconds
[2024-09-30T20:21:05.871+0000] {processor.py:157} INFO - Started process (PID=795) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:05.872+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:21:05.874+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:05.874+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:06.381+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:06.374+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:21:06.383+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:06.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.541 seconds
[2024-09-30T20:21:36.717+0000] {processor.py:157} INFO - Started process (PID=822) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:36.718+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:21:36.719+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:36.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:37.174+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:21:37.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:21:37.176+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:21:37.204+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.491 seconds
[2024-09-30T20:22:07.587+0000] {processor.py:157} INFO - Started process (PID=849) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:07.588+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:22:07.589+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:07.589+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:08.083+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:08.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:22:08.085+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:08.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.523 seconds
[2024-09-30T20:22:38.417+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:38.418+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:22:38.419+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:38.419+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:38.885+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:22:38.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:22:38.886+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:22:38.914+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.500 seconds
[2024-09-30T20:23:09.232+0000] {processor.py:157} INFO - Started process (PID=903) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:09.233+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:23:09.234+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:09.234+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:09.786+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:09.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:23:09.788+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:09.816+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.588 seconds
[2024-09-30T20:23:40.110+0000] {processor.py:157} INFO - Started process (PID=930) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:40.111+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:23:40.112+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:40.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:40.575+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:23:40.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:23:40.577+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:23:40.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.492 seconds
[2024-09-30T20:24:10.916+0000] {processor.py:157} INFO - Started process (PID=957) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:10.918+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:24:10.919+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:10.919+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:11.449+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:11.442+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:24:11.451+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:11.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.564 seconds
[2024-09-30T20:24:41.810+0000] {processor.py:157} INFO - Started process (PID=984) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:41.811+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:24:41.813+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:41.813+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:42.314+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:24:42.306+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:24:42.316+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:24:42.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.535 seconds
[2024-09-30T20:25:12.667+0000] {processor.py:157} INFO - Started process (PID=1011) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:12.669+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:25:12.671+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:12.670+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:13.213+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:13.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:25:13.215+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:13.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.575 seconds
[2024-09-30T20:25:43.536+0000] {processor.py:157} INFO - Started process (PID=1038) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:43.537+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:25:43.539+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:43.538+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:44.040+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:25:44.034+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:25:44.042+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:25:44.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.534 seconds
[2024-09-30T20:26:14.385+0000] {processor.py:157} INFO - Started process (PID=1065) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:14.387+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:26:14.388+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:14.388+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:14.843+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:14.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:26:14.845+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:14.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.483 seconds
[2024-09-30T20:26:45.216+0000] {processor.py:157} INFO - Started process (PID=1092) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:45.218+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:26:45.219+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:45.218+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:45.667+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:26:45.661+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:26:45.669+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:26:45.697+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.484 seconds
[2024-09-30T20:27:16.012+0000] {processor.py:157} INFO - Started process (PID=1119) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:16.014+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:27:16.015+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:16.014+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:16.507+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:16.501+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:27:16.509+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:16.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.523 seconds
[2024-09-30T20:27:46.836+0000] {processor.py:157} INFO - Started process (PID=1146) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:46.837+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:27:46.839+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:46.838+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:47.380+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:27:47.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:27:47.382+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:27:47.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.576 seconds
[2024-09-30T20:28:17.725+0000] {processor.py:157} INFO - Started process (PID=1173) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:17.726+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:28:17.727+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:17.726+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:18.171+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:18.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:28:18.173+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:18.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.473 seconds
[2024-09-30T20:28:48.507+0000] {processor.py:157} INFO - Started process (PID=1200) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:48.509+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:28:48.510+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:48.509+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:49.001+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:28:48.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:28:49.003+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:28:49.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.524 seconds
[2024-09-30T20:29:19.337+0000] {processor.py:157} INFO - Started process (PID=1227) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:19.339+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:29:19.341+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:19.341+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:19.854+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:19.847+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:29:19.856+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:19.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.557 seconds
[2024-09-30T20:29:50.210+0000] {processor.py:157} INFO - Started process (PID=1254) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:50.211+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:29:50.212+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:50.212+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:50.707+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:29:50.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:29:50.709+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:29:50.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.527 seconds
[2024-09-30T20:30:21.043+0000] {processor.py:157} INFO - Started process (PID=1281) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:21.044+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:30:21.045+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:21.045+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:21.552+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:21.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:30:21.554+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:21.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.537 seconds
[2024-09-30T20:30:51.929+0000] {processor.py:157} INFO - Started process (PID=1308) to work on /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:51.931+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/binance.Dag2.py for tasks to queue
[2024-09-30T20:30:51.932+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:51.932+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:52.532+0000] {logging_mixin.py:149} INFO - [2024-09-30T20:30:52.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/binance.Dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/binance.Dag2.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[2024-09-30T20:30:52.534+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/binance.Dag2.py
[2024-09-30T20:30:52.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/binance.Dag2.py took 0.647 seconds
