[2024-11-04T17:49:43.800+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2024-11-04T17:49:44.399+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_binance_dag1.STRK scheduled__2024-11-03T09:00:00+00:00 [queued]>
[2024-11-04T17:49:44.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_binance_dag1.STRK scheduled__2024-11-03T09:00:00+00:00 [queued]>
[2024-11-04T17:49:44.454+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2024-11-04T17:49:44.566+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): STRK> on 2024-11-03 09:00:00+00:00
[2024-11-04T17:49:44.607+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2024-11-04T17:49:44.621+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_binance_dag1', 'STRK', 'scheduled__2024-11-03T09:00:00+00:00', '--job-id', '988', '--raw', '--subdir', 'DAGS_FOLDER/binance.Dag1.py', '--cfg-path', '/tmp/tmpoei2uamt']
[2024-11-04T17:49:44.632+0000] {standard_task_runner.py:85} INFO - Job 988: Subtask STRK
[2024-11-04T17:49:45.105+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-11-04T17:49:55.172+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 988 for task STRK ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 75)
[2024-11-04T17:50:02.711+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-04T17:50:02.786+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
